runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files:  app_portfolio/profile.html
  upload:  app_portfolio/profile.html

- url: /(.*)
  static_files:  app_portfolio/\1
  upload:  app_portfolio/(.*)
